const myData = [
  [{"title":"Legal Access to By-Mail Abortion Pills Online"},
   {"tags":"abortion abortion pill the pill aborion ban feminism toxic masculinity us usa united states violence against women donate donations"},
   {"link":"https://aidaccess.org/"}],
  [{"title":"Prison Feminism"},
   {"tags":"prison feminism toxic masculinity us usa united states violence against women donate donations"},
   {"link":"https://www.successstoriesprogram.org/"}],
  [{"title":"Stop Jim Crow 2"},
   {"tags":"voting rights voter freedom voter suppression hr1 for the people act united states us usa"},
   {"link":"https://www.stopjimcrow2.com/"}],
  [{"title":"Resources for Folks Returning Home"},
   {"tags":"prison prison reform recidivism returning home leaving prison usa united states us"},
   {"link":"https://www.successstoriesprogram.org/resources"}],
  [{"title":"Feminist-Abolitionist Reading List"},
   {"tags":"feminism abolitionist us united states usa prison prison reform violence against women"},
   {"link":"https://docs.google.com/document/d/1qdAmcufkL9Q8gus-Ysu5VcZxAkOmsRUdMDXl8qoTMCw/edit"}],
  [{"title":"Watch: The Feminist on Cellblock Y"},
   {"tags":"prison reform feminism toxic masculinity usa us united states"},
   {"link":"https://www.youtube.com/watch?v=JYxTzsabkH8"}],
  [{"title":"Don't Call The Police"},
   {"tags":"police united states usa us"},
   {"link":"https://dontcallthepolice.com/"}],
  [{"title":"The Marshall Project"},
   {"tags":"criminal justice united states us usa"},
   {"link":"https://www.themarshallproject.org/"}],
  [{"title":"Abortion Funds"},
   {"tags":"abortion rights woman rights women right women's right to choose donate donation usa united states us"},
   {"link":"https://abortionfunds.org/"}],
  [{"title":"The Last Prisoner Project"},
   {"tags":"marijuana weed cannabis pot drug policy bail prisons jail prison system policing police donate prison reform us united states usa"},
   {"link":"https://www.lastprisonerproject.org/"}],
  [{"title":"Demilitarize Our Neighborhoods"},
   {"tags":"blm black lives matter police usa us united states"},
   {"link":"https://blacklivesmatter.com/demilitarize-our-neighborhoods/?__cf_chl_jschl_tk__=8e0611ff2687476313929f9c117754b5dd7f4537-1620168296-0-AWIftifDQS6W0QP2LDu7esw4OSTxcioNMvSoYqXKc9Ruj9W0pDDO4Sp6RtfiFQiRr7BcIhfbbe2GDDZqhMf8VH8-Sy0Qe-bW3HnEUuuyMdPnhyhLQ-XdD6GyWdfktOClt-bMhhgVhXh_otQJjXi-m0bI55xvN8MX9MJZGKXOf4oKd1VMT85GEEqFQCE588dO8xaF25yEc9MKFeOP0Qs7aFSnbkwgVa720eIw9fkqH-QbVOs2Gn_cITPDobK8WrsuY2XidLeJdBm6oa3eVCEqXMZXATLeGjyURDv4fp-Qf_-xYs14-YSee8vKXrmSwEmhdjAXkCAP9ZqOf_yO2b7DCvNbFvH-DNXFoVHZ8N4p_gjmTEX9CHlc0kEl7pKgzhsFxzotXIFX35gACDsVJGUAkZoqV26zGKLfu6tv9OJ3WW2J3VYgTxYfT1L-cVnO4BcUtLEqAoYqkuEurudoH1pT6-jzlsWu0kXh_rd-UAr_0D8YAfZ5p79XAlOTKT24AUKx1g"}],
  [{"title":"Change[dot]org"},
   {"tags":"united states usa us petitions petition"},
   {"link":"https://www.change.org/"}],
  [{"title":"The Bail Project"},
   {"tags":"bail prisons jail prison system policing police donate us united states usa"},
   {"link":"https://bailproject.org/"}],
  [{"title":"American-Arab Anti-Discrimination Committee"},
   {"tags":"united states usa us arab american voter registration voting rights israeli aparthaid"},
   {"link":"https://www.adc.org/"}],
  [{"title":"Campaign Zero"},
   {"tags":"police violence police accountability united states usa us donate"},
   {"link":"https://www.joincampaignzero.org/#vision"}],
  [{"title":"New Orleans Parish Prison Reform Coalition"},
   {"tags":"donate new orleans louisiana united states usa nola us prisons justice system jail bail"},
   {"link":"https://opprcnola.org/"}],
  [{"title":"Your Fat Friend"},
   {"tags":"anti-fat bias anti fat bias activism fat acitivism united states australia uk united kingdom us usa queer justice lgbtqia lgbtq lgbtq+ lgbtqia+ education"},
   {"link":"https://www.yourfatfriend.com/"}],
  [{"title":"Planned Parenthood"},
   {"tags":"womens rights abortion rights donate united states usa us trans rights"},
   {"link":"https://www.plannedparenthood.org/"}],
  [{"title":"Black & Pink"},
   {"tags":"anarchist queer politics abolish prisons boston massachusetts united states usa us black and pink blm lgbtq+ lgbtq lgbtqia lgbtqia+ lgbtqia2s lgbtqia2s+ queer rights"},
   {"link":"https://www.blackandpink.org/"}],
  [{"title":"AdoptUSKids"},
   {"tags":"adoption foster visibility united states usa us donate"},
   {"link":"https://www.adoptuskids.org/"}],
  [{"title":"Disability Visibility Project"},
   {"tags":"differently abled rights disability rights united states usa us disabled activist donate accessibility"},
   {"link":"https://disabilityvisibilityproject.com/"}],
  [{"title":"Panhandle Equality"},
   {"tags":"trans rights transgender rights lgbtq lgbtq+ lgbtqia lgbtqia+ nebraska midwest united states us usa donate cyberbullying"},
   {"link":"https://sites.google.com/a/panhandleequality.org/panhandleequality/"}],
  [{"title":"No More"},
   {"tags":"domestic violence sexual assault united states usa us donate"},
   {"link":"https://nomore.org/"}],
  [{"title":"The Big O Project"},
   {"tags":"fatness anti-fat bias anti fat bias fat phobia fatphobia united kingdom uk united states us usa"},
   {"link":"https://thebigoproject.com/about.html"}],
  [{"title":"The Trevor Project"},
   {"tags":"crisis suicide hotline teen suicide prevention dating violence lgbtq lgbtq+ lgbtqia lgbtqia+ education curriculum donate united states usa us"},
   {"link":"https://www.thetrevorproject.org/"}],
  [{"title":"Brown Girls Do"},
   {"tags":"diversity arts donate brown girls ballet gymnastics minority united states us usa"},
   {"link":"http://www.browngirlsdoinc.org/"}],
  [{"title":"Student Press Law Center"},
   {"tags":"education united states us usa press freedom of the press donate"},
   {"link":"https://splc.org/"}],
  [{"title":"RAINN"},
   {"tags":"abuse and incest national network anti sexual violence anti sexual assault donate us usa united states"},
   {"link":"https://www.rainn.org/"}],
  [{"title":"Murdered & Missing Indigenous Womxn"},
   {"tags":"american indian native alaskan women violence sex trafficking awareness donate united states usa us"},
   {"link":"https://www.nativewomenswilderness.org/mmiw"}],
  [{"title":"National Alliance on Mental Illness"},
   {"tags":"mental health awareness united states usa us donate suicide hotline stigma nami therapy therapist psychology psychologist"},
   {"link":"https://www.nami.org/Home"}],
  [{"title":"Crisis Text Line"},
   {"tags":"suicide prevention hotline donate mental illness mental health awreness united states usa us"},
   {"link":"https://www.crisistextline.org/"}],
  [{"title":"Needy Meds"},
   {"tags":"ma massachusetts us usa united states affordable healthcare medicine"},
   {"link":"https://www.needymeds.org/"}],
  [{"title":"Project Bread"},
   {"tags":"ma massachusetts food insecurity poverty food desert usa us united states hunger food accessibility"},
   {"link":"https://www.projectbread.org/"}],
  [{"title":"Bagly"},
   {"tags":"boston ma massachusetts united states us usa lgbtqia youth lgbtqia+ youth lgbtq+ youth lgbtq youth-led youth leadership gay rights"},
   {"link":"https://www.bagly.org/"}],
  [{"title":"The Fear of Fat - The Real Elephant In The Room"},
   {"tags":"anti-fat bias anti fat bias activism fat acitivism united states australia uk united kingdom us usa ted talk tedx mental health awareness education"},
   {"link":"https://www.youtube.com/watch?v=HXGwJevjOfs"}],
  [{"title":"How to (Explain) ADHD"},
   {"tags":"mental health awareness add adhd attention-deficit hyperactivity disorder attention deficit hyperactivity disorder emotional dysregulation us usa united states education"},
   {"link":"https://www.youtube.com/watch?v=jhcn1_qsYmg"}]
];

const column = document.getElementById("columns");
const link = document.getElementById("link");
for (let i = 0; i < myData.length; i++) {
  column.innerHTML += `
  <div class="figure">
    <div class="terms">
      <div class="text">
        <a class="link link-style" href=${myData[i][2].link} target="_blank" alt="Demilitarize neighborhoods">
          <span class="vertical-align"> ${myData[i][0].title} </span>
          <div class="tags">${myData[i][1].tags}</div>
        </a>
      </div>
    </div>
  </div>
  `
};
